name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Install & Build JS Sample
        working-directory: JavaScript\(v4.0\)
        run: |
          npm ci
          npm run build
      - name: Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_RED_HILL_0B7F9A910 }}
          repo_token:                 ${{ secrets.GITHUB_TOKEN }}
          action:                     "upload"
          skip_app_build:             true
          app_location:               "JavaScript(v4.0)/build"
          api_location:               ""
          output_location:            ""
